spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev #spring.cloud.config.profile dev开发环境配置文件 test测试环境 pro正式环境
      uri: http://localhost:8888/

server:
  port: 8881
